### ISSUE TITLE
Setting up a local testing environment?

### ISSUE THREAD

**Issue by leizhao4** [uncovery/uncovery_me#100]
Hi Unc,

I think I can help with some JavaScript/CSS, but I have no idea how to test my changes. I do have a PHP/MySQL environment set up, but the code seems to require things that are out of the scope of this repo (xmpp_error, uncovery_mysql, un_serial_curl, etc.). Any suggestions?

My in-game name is leizh, by the way.

**Comment by uncovery** [comment]
Check out my other repositories, you will find all of the stuff there: https://github.com/uncovery
If something is still missing, let me know

**Comment by leizhao4** [comment]
Thanks! I don't see uncovery_mysql. What is that?

Also, is there a way to bypass some of the dependencies if I just want to test the front end stuff?

**Comment by uncovery** [comment]
I am working on _mysql right now.
I am afraid you cannot work without them. They were all part of the project initially, I just 'outsourced' them since I use the same in several projects. In general I do not mind to rework the code to make those optional, but in most of the cases the workload would be far more than including the dependencies.

**Comment by leizhao4** [comment]
No worries! I'll try to include them. Thanks for all the great work!

**Comment by uncovery** [comment]
You are welcome!
See this here: https://github.com/uncovery/uncovery_mysql/blob/master/uncovery_mysql.inc.php
Please close this issue once all the dependencies are cleared up.
