### ISSUE TITLE
Improve logs for voting rewards 

### ISSUE THREAD

**Issue by psiber-on-uncovery** [uncovery/uncovery_me#145]
Include roll value
Include reward given

**Comment by uncovery** [comment]
also include "unknown" if the site field is empty.

**Comment by uncovery** [comment]
reward given is a bit tricky. It's an item_type, a data value and enchantments, so potentially 3 fields.
Alternatively we could just put the data into an array and serialize it, store it in a text field. but then we cannot make any statistical use of it.

Or we just store a string for the general type of item received instead of all the details, that might be the best solution?

**Comment by psiber-on-uncovery** [comment]
I'm leaning towards a string, not ideal, but at least it's a legible output.

**Comment by uncovery** [comment]
done
