### ISSUE TITLE
Enable depositslots to be bought

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#155]
We need to move from a fixed list of deposit slots to a system similar to the homes where people can buy deposit slots.

The big question: What will be the price metric for the slots?
- stored amount of blocks?
- slots (i.e. types of blocks)?
- a combination of the 2 above?

**Comment by psiber-on-uncovery** [comment]
Stored amount I think we should leave alone. some users already have millions sitting in it and it doesnt seem fair to lock out their deposit and force them to build rooms of chests just to bulk dump mats into it, or flood shop with even MORE cobblestone.

price metric i have implemented tentatively the same as homes. I feel they are equal in value personally.

STATE (as much for my own ref as anything else)

known bugs to resolve
> the calc function calcs based on filled deposit boxes, not an owned count

as part of this rebuild I think that slots need to end up "claimed" and reusable slots with transactions just logged, which should keep the count down too. 165K slots already created so far... if we got busier that number could explode.

in order to achieve this current plan is
> add a method to create "claimed" slots (ie when bought)
> add "claimed slots" based on current user levels to existing table (update to existing count)
> update calc function to reference "claimed" slots
> add an import command to be used by uncovery on go live of the system that pushes data out of the old and into the new system. command to transfer current deposit items into "claimed" slots. (data transfer old to new)
> add a buy command based on updated calc function
> define empty slots as reusable in existing code, but contribute to the count similar to homes system.

Related coding to be done at same time
> define a way to return goods from the receivers end without making it exploitable like it was with inactive users historically. ie "no i dont want your x item", should mail sender too with reason as a command arg.

**Comment by darthandrew1** [comment]
Done?

**Comment by uncovery** [comment]
I am still fixing the odd small bug here and there, let's wait another 24 hours to make sure it works.
