### ISSUE TITLE
Website Shoutbox

### ISSUE THREAD

**Issue by darthandrew1** [uncovery/uncovery_me#216]
Basically, we should add a shoutbox to the top of the page for logged in users. It would bring us closer and we could post little "hellos" here and there.

**Comment by uncovery** [comment]
I disagree. We had that, it was hardly used. 
The forum is not used enough either.
We generally do not have enough users for this kind of thing and are split enough already across all the different channels we have. Anything we add should integrate with existing comms methods instead of adding new, isolated ones.
