### ISSUE TITLE
Add spawn eggs back to the shop

### ISSUE THREAD

**Issue by uncovery** [uncovery/uncovery_me#95]
We can add spawn eggs back to the shop since we fixed the modifiable spawners

**Comment by psiber-on-uncovery** [comment]
Current non aggressive eggs still missing from the shop - i think it also might be worth looking at higher pricing brackets for all eggs (say 500 ea to encourage people to breed animals rather than buy and spawn them). The market would bear a price increase.

Bat_Egg
Chicken_Egg
Cow_Egg
Horse_Egg
Mooshroom_Egg
Ocelot_Egg
Pig_egg
Rabbit_egg
Sheep_Egg
Squid_Egg
Wolf_Egg

Is there a way I can help here to relist these or is it something specific you do as "uncovery" that creates an infinite supply?

Easy enhancement to close out otherwise.

**Comment by uncovery** [comment]
I just insert them into the DB with a -1 quantity and manual item IDs that are very low (1-20) to I can find them easier

**Comment by psiber-on-uncovery** [comment]
Bat_Egg                            65
Chicken_Egg                    93
Cow_Egg                          92
Horse_Egg                       100
Mooshroom_Egg              96
Ocelot_Egg                      98
Pig_egg                           90
Rabbit_egg                      101
Sheep_Egg                      91
Squid_Egg                       94
Wolf_Egg                         95

**Comment by uncovery** [comment]
Done
